In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('Churn_Modelling.csv')

In [3]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [8]:
x = df.iloc[:,3:13]
x

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,619,France,Female,42,2,0.00,1,1,1,101348.88
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58
2,502,France,Female,42,8,159660.80,3,1,0,113931.57
3,699,France,Female,39,1,0.00,2,0,0,93826.63
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10
...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77
9997,709,France,Female,36,7,0.00,1,0,1,42085.58
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78

In [9]:
y = df['Exited']
y

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [10]:
from sklearn.preprocessing import LabelEncoder

In [11]:
X_column_transformer = LabelEncoder()

In [12]:
x['Geography']=X_column_transformer.fit_transform(x['Geography'])
x

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,619,0,Female,42,2,0.00,1,1,1,101348.88
1,608,2,Female,41,1,83807.86,1,0,1,112542.58
2,502,0,Female,42,8,159660.80,3,1,0,113931.57
3,699,0,Female,39,1,0.00,2,0,0,93826.63
4,850,2,Female,43,2,125510.82,1,1,1,79084.10
...,...,...,...,...,...,...,...,...,...,...
9995,771,0,Male,39,5,0.00,2,1,0,96270.64
9996,516,0,Male,35,10,57369.61,1,1,1,101699.77
9997,709,0,Female,36,7,0.00,1,0,1,42085.58
9998,772,1,Male,42,3,75075.31,2,1,0,92888.52
9999,792,0,Female,28,4,130142.79,1,1,0,38190.78

In [13]:
x['Gender']=X_column_transformer.fit_transform(x['Gender'])
x

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,619,0,0,42,2,0.00,1,1,1,101348.88
1,608,2,0,41,1,83807.86,1,0,1,112542.58
2,502,0,0,42,8,159660.80,3,1,0,113931.57
3,699,0,0,39,1,0.00,2,0,0,93826.63
4,850,2,0,43,2,125510.82,1,1,1,79084.10
...,...,...,...,...,...,...,...,...,...,...
9995,771,0,1,39,5,0.00,2,1,0,96270.64
9996,516,0,1,35,10,57369.61,1,1,1,101699.77
9997,709,0,0,36,7,0.00,1,0,1,42085.58
9998,772,1,1,42,3,75075.31,2,1,0,92888.52
9999,792,0,0,28,4,130142.79,1,1,0,38190.78

In [ ]:
import numpy as np
x['Balance'].replace(0,np.NaN,inplace=)

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.2,random_state=1)

In [17]:
import keras

In [19]:
from keras.models import Sequential
from keras.layers import Dense,Dropout

In [20]:
classifier = Sequential()

In [21]:
classifier.add(Dense(6,activation='relu',input_shape=(x_train.shape[1],)))
classifier.add(Dropout(rate=0.1))

In [22]:
classifier.add(Dense(6,activation='relu'))
classifier.add(Dropout(rate=0.1))

In [23]:
classifier.add(Dense(1,activation='sigmoid'))

In [24]:
classifier.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 6)                 66

 dropout (Dropout)           (None, 6)                 0

 dense_1 (Dense)             (None, 6)                 42

 dropout_1 (Dropout)         (None, 6)                 0

 dense_2 (Dense)             (None, 1)                 7

=================================================================
Total params: 115
Trainable params: 115
Non-trainable params: 0
_________________________________________________________________

In [25]:
classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [26]:
history=classifier.fit(x_train,y_train,batch_size=32,epochs=200,validation_split=0.1,verbose=2)

Epoch 1/200
225/225 - 3s - loss: 2667.1077 - accuracy: 0.5824 - val_loss: 186.3065 - val_accuracy: 0.7425 - 3s/epoch - 15ms/step
Epoch 2/200
225/225 - 1s - loss: 469.4554 - accuracy: 0.7085 - val_loss: 19.5573 - val_accuracy: 0.7750 - 612ms/epoch - 3ms/step
Epoch 3/200
225/225 - 1s - loss: 231.6415 - accuracy: 0.7368 - val_loss: 6.2861 - val_accuracy: 0.7750 - 528ms/epoch - 2ms/step
Epoch 4/200
225/225 - 1s - loss: 147.9617 - accuracy: 0.7524 - val_loss: 1.0009 - val_accuracy: 0.7763 - 523ms/epoch - 2ms/step
Epoch 5/200
225/225 - 1s - loss: 110.6591 - accuracy: 0.7601 - val_loss: 2.8233 - val_accuracy: 0.7775 - 568ms/epoch - 3ms/step
Epoch 6/200
225/225 - 1s - loss: 69.1353 - accuracy: 0.7757 - val_loss: 0.5498 - val_accuracy: 0.7788 - 522ms/epoch - 2ms/step
Epoch 7/200
225/225 - 1s - loss: 62.2280 - accuracy: 0.7810 - val_loss: 0.5385 - val_accuracy: 0.7788 - 532ms/epoch - 2ms/step
Epoch 8/200
225/225 - 1s - loss: 51.0458 - accuracy: 0.7792 - val_loss: 0.5327 - val_accuracy: 0.7788 - 556ms/epoch - 2ms/step
Epoch 9/200
225/225 - 1s - loss: 37.2025 - accuracy: 0.7799 - val_loss: 0.5299 - val_accuracy: 0.7788 - 668ms/epoch - 3ms/step
Epoch 10/200
225/225 - 1s - loss: 29.8339 - accuracy: 0.7819 - val_loss: 0.5287 - val_accuracy: 0.7788 - 623ms/epoch - 3ms/step
Epoch 11/200
225/225 - 1s - loss: 26.2302 - accuracy: 0.7821 - val_loss: 0.5285 - val_accuracy: 0.7788 - 648ms/epoch - 3ms/step
Epoch 12/200
225/225 - 1s - loss: 20.8182 - accuracy: 0.7817 - val_loss: 0.5287 - val_accuracy: 0.7788 - 780ms/epoch - 3ms/step
Epoch 13/200
225/225 - 1s - loss: 15.5274 - accuracy: 0.7860 - val_loss: 0.5290 - val_accuracy: 0.7788 - 642ms/epoch - 3ms/step
Epoch 14/200
225/225 - 1s - loss: 11.0642 - accuracy: 0.7875 - val_loss: 0.5293 - val_accuracy: 0.7788 - 596ms/epoch - 3ms/step
Epoch 15/200
225/225 - 1s - loss: 9.9802 - accuracy: 0.7867 - val_loss: 0.5295 - val_accuracy: 0.7788 - 857ms/epoch - 4ms/step
Epoch 16/200
225/225 - 1s - loss: 6.7123 - accuracy: 0.7887 - val_loss: 0.5297 - val_accuracy: 0.7788 - 902ms/epoch - 4ms/step
Epoch 17/200
225/225 - 1s - loss: 5.9673 - accuracy: 0.7881 - val_loss: 0.5299 - val_accuracy: 0.7788 - 617ms/epoch - 3ms/step
Epoch 18/200
225/225 - 1s - loss: 5.6568 - accuracy: 0.7869 - val_loss: 0.5302 - val_accuracy: 0.7788 - 881ms/epoch - 4ms/step
Epoch 19/200
225/225 - 1s - loss: 3.2437 - accuracy: 0.7887 - val_loss: 0.5302 - val_accuracy: 0.7788 - 831ms/epoch - 4ms/step
Epoch 20/200
225/225 - 1s - loss: 3.3525 - accuracy: 0.7886 - val_loss: 0.5303 - val_accuracy: 0.7788 - 630ms/epoch - 3ms/step
Epoch 21/200
225/225 - 1s - loss: 2.0646 - accuracy: 0.7868 - val_loss: 0.5304 - val_accuracy: 0.7788 - 552ms/epoch - 2ms/step
Epoch 22/200
225/225 - 1s - loss: 2.0748 - accuracy: 0.7910 - val_loss: 0.5305 - val_accuracy: 0.7788 - 586ms/epoch - 3ms/step
Epoch 23/200
225/225 - 1s - loss: 1.2522 - accuracy: 0.7917 - val_loss: 0.5303 - val_accuracy: 0.7788 - 564ms/epoch - 3ms/step
Epoch 24/200
225/225 - 1s - loss: 1.2200 - accuracy: 0.7976 - val_loss: 0.5301 - val_accuracy: 0.7788 - 652ms/epoch - 3ms/step
Epoch 25/200
225/225 - 1s - loss: 1.7950 - accuracy: 0.7956 - val_loss: 0.5300 - val_accuracy: 0.7788 - 546ms/epoch - 2ms/step
Epoch 26/200
225/225 - 1s - loss: 1.1249 - accuracy: 0.7965 - val_loss: 0.5298 - val_accuracy: 0.7788 - 542ms/epoch - 2ms/step
Epoch 27/200
225/225 - 1s - loss: 1.0954 - accuracy: 0.7958 - val_loss: 0.5297 - val_accuracy: 0.7788 - 533ms/epoch - 2ms/step
Epoch 28/200
225/225 - 1s - loss: 0.7342 - accuracy: 0.7968 - val_loss: 0.5296 - val_accuracy: 0.7788 - 535ms/epoch - 2ms/step
Epoch 29/200
225/225 - 1s - loss: 0.9001 - accuracy: 0.7965 - val_loss: 0.5297 - val_accuracy: 0.7788 - 524ms/epoch - 2ms/step
Epoch 30/200
225/225 - 1s - loss: 1.0821 - accuracy: 0.7965 - val_loss: 0.5296 - val_accuracy: 0.7788 - 529ms/epoch - 2ms/step
Epoch 31/200
225/225 - 1s - loss: 0.6731 - accuracy: 0.7965 - val_loss: 0.5296 - val_accuracy: 0.7788 - 573ms/epoch - 3ms/step
Epoch 32/200
225/225 - 1s - loss: 0.9396 - accuracy: 0.7971 - val_loss: 0.5295 - val_accuracy: 0.7788 - 559ms/epoch - 2ms/step
Epoch 33/200
225/225 - 1s - loss: 0.6065 - accuracy: 0.7972 - val_loss: 0.5295 - val_accuracy: 0.7788 - 583ms/epoch - 3ms/step
Epoch 34/200
225/225 - 1s - loss: 0.5220 - accuracy: 0.7981 - val_loss: 0.5296 - val_accuracy: 0.7788 - 577ms/epoch - 3ms/step
Epoch 35/200
225/225 - 1s - loss: 0.7192 - accuracy: 0.7969 - val_loss: 0.5296 - val_accuracy: 0.7788 - 572ms/epoch - 3ms/step
Epoch 36/200
225/225 - 1s - loss: 0.6057 - accuracy: 0.7979 - val_loss: 0.5295 - val_accuracy: 0.7788 - 546ms/epoch - 2ms/step
Epoch 37/200
225/225 - 1s - loss: 0.6673 - accuracy: 0.7967 - val_loss: 0.5297 - val_accuracy: 0.7788 - 517ms/epoch - 2ms/step
Epoch 38/200
225/225 - 1s - loss: 0.6074 - accuracy: 0.7979 - val_loss: 0.5296 - val_accuracy: 0.7788 - 889ms/epoch - 4ms/step
Epoch 39/200
225/225 - 1s - loss: 0.5997 - accuracy: 0.7972 - val_loss: 0.5295 - val_accuracy: 0.7788 - 783ms/epoch - 3ms/step
Epoch 40/200
225/225 - 1s - loss: 0.5455 - accuracy: 0.7964 - val_loss: 0.5296 - val_accuracy: 0.7788 - 1s/epoch - 5ms/step
Epoch 41/200
225/225 - 1s - loss: 0.5219 - accuracy: 0.7967 - val_loss: 0.5297 - val_accuracy: 0.7788 - 1s/epoch - 5ms/step
Epoch 42/200
225/225 - 1s - loss: 0.5390 - accuracy: 0.7992 - val_loss: 0.5296 - val_accuracy: 0.7788 - 964ms/epoch - 4ms/step
Epoch 43/200
225/225 - 1s - loss: 0.5554 - accuracy: 0.7978 - val_loss: 0.5297 - val_accuracy: 0.7788 - 844ms/epoch - 4ms/step
Epoch 44/200
225/225 - 1s - loss: 0.5507 - accuracy: 0.7986 - val_loss: 0.5296 - val_accuracy: 0.7788 - 706ms/epoch - 3ms/step
Epoch 45/200
225/225 - 1s - loss: 0.5712 - accuracy: 0.7978 - val_loss: 0.5297 - val_accuracy: 0.7788 - 576ms/epoch - 3ms/step
Epoch 46/200
225/225 - 1s - loss: 0.5440 - accuracy: 0.7982 - val_loss: 0.5296 - val_accuracy: 0.7788 - 674ms/epoch - 3ms/step
Epoch 47/200
225/225 - 1s - loss: 0.5308 - accuracy: 0.7978 - val_loss: 0.5297 - val_accuracy: 0.7788 - 653ms/epoch - 3ms/step
Epoch 48/200
225/225 - 1s - loss: 0.5230 - accuracy: 0.7974 - val_loss: 0.5297 - val_accuracy: 0.7788 - 545ms/epoch - 2ms/step
Epoch 49/200
225/225 - 1s - loss: 0.5258 - accuracy: 0.7985 - val_loss: 0.5297 - val_accuracy: 0.7788 - 642ms/epoch - 3ms/step
Epoch 50/200
225/225 - 1s - loss: 0.5194 - accuracy: 0.7983 - val_loss: 0.5297 - val_accuracy: 0.7788 - 627ms/epoch - 3ms/step
Epoch 51/200
225/225 - 1s - loss: 0.5096 - accuracy: 0.7987 - val_loss: 0.5296 - val_accuracy: 0.7788 - 585ms/epoch - 3ms/step
Epoch 52/200
225/225 - 1s - loss: 0.5106 - accuracy: 0.7990 - val_loss: 0.5296 - val_accuracy: 0.7788 - 637ms/epoch - 3ms/step
Epoch 53/200
225/225 - 1s - loss: 0.5091 - accuracy: 0.7989 - val_loss: 0.5297 - val_accuracy: 0.7788 - 618ms/epoch - 3ms/step
Epoch 54/200
225/225 - 1s - loss: 0.5084 - accuracy: 0.7990 - val_loss: 0.5297 - val_accuracy: 0.7788 - 595ms/epoch - 3ms/step
Epoch 55/200
225/225 - 1s - loss: 0.5038 - accuracy: 0.7986 - val_loss: 0.5297 - val_accuracy: 0.7788 - 596ms/epoch - 3ms/step
Epoch 56/200
225/225 - 1s - loss: 0.5182 - accuracy: 0.7989 - val_loss: 0.5298 - val_accuracy: 0.7788 - 513ms/epoch - 2ms/step
Epoch 57/200
225/225 - 1s - loss: 0.5456 - accuracy: 0.7994 - val_loss: 0.5298 - val_accuracy: 0.7788 - 525ms/epoch - 2ms/step
Epoch 58/200
225/225 - 1s - loss: 0.5166 - accuracy: 0.7985 - val_loss: 0.5298 - val_accuracy: 0.7788 - 546ms/epoch - 2ms/step
Epoch 59/200
225/225 - 1s - loss: 0.5026 - accuracy: 0.7992 - val_loss: 0.5298 - val_accuracy: 0.7788 - 608ms/epoch - 3ms/step
Epoch 60/200
225/225 - 1s - loss: 0.5140 - accuracy: 0.7989 - val_loss: 0.5298 - val_accuracy: 0.7788 - 521ms/epoch - 2ms/step
Epoch 61/200
225/225 - 1s - loss: 0.5020 - accuracy: 0.7993 - val_loss: 0.5297 - val_accuracy: 0.7788 - 559ms/epoch - 2ms/step
Epoch 62/200
225/225 - 1s - loss: 0.5322 - accuracy: 0.7983 - val_loss: 0.5297 - val_accuracy: 0.7788 - 588ms/epoch - 3ms/step
Epoch 63/200
225/225 - 1s - loss: 0.5279 - accuracy: 0.7992 - val_loss: 0.5298 - val_accuracy: 0.7788 - 715ms/epoch - 3ms/step
Epoch 64/200
225/225 - 1s - loss: 0.5113 - accuracy: 0.7993 - val_loss: 0.5298 - val_accuracy: 0.7788 - 820ms/epoch - 4ms/step
Epoch 65/200
225/225 - 1s - loss: 0.5040 - accuracy: 0.7990 - val_loss: 0.5298 - val_accuracy: 0.7788 - 625ms/epoch - 3ms/step

Epoch 66/200
225/225 - 1s - loss: 0.5102 - accuracy: 0.7993 - val_loss: 0.5298 - val_accuracy: 0.7788 - 534ms/epoch - 2ms/step
Epoch 67/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5298 - val_accuracy: 0.7788 - 516ms/epoch - 2ms/step
Epoch 68/200
225/225 - 1s - loss: 0.5079 - accuracy: 0.7992 - val_loss: 0.5298 - val_accuracy: 0.7788 - 511ms/epoch - 2ms/step
Epoch 69/200
225/225 - 1s - loss: 0.5085 - accuracy: 0.7992 - val_loss: 0.5298 - val_accuracy: 0.7788 - 518ms/epoch - 2ms/step
Epoch 70/200
225/225 - 1s - loss: 0.5015 - accuracy: 0.7993 - val_loss: 0.5297 - val_accuracy: 0.7788 - 530ms/epoch - 2ms/step
Epoch 71/200
225/225 - 1s - loss: 0.5044 - accuracy: 0.7989 - val_loss: 0.5298 - val_accuracy: 0.7788 - 549ms/epoch - 2ms/step
Epoch 72/200
225/225 - 1s - loss: 0.5034 - accuracy: 0.7992 - val_loss: 0.5298 - val_accuracy: 0.7788 - 546ms/epoch - 2ms/step
Epoch 73/200
225/225 - 1s - loss: 0.5135 - accuracy: 0.7990 - val_loss: 0.5297 - val_accuracy: 0.7788 - 532ms/epoch - 2ms/step
Epoch 74/200
225/225 - 1s - loss: 0.5030 - accuracy: 0.7989 - val_loss: 0.5297 - val_accuracy: 0.7788 - 548ms/epoch - 2ms/step
Epoch 75/200
225/225 - 1s - loss: 0.5054 - accuracy: 0.7992 - val_loss: 0.5297 - val_accuracy: 0.7788 - 824ms/epoch - 4ms/step
Epoch 76/200
225/225 - 1s - loss: 0.5023 - accuracy: 0.7994 - val_loss: 0.5297 - val_accuracy: 0.7788 - 624ms/epoch - 3ms/step
Epoch 77/200
225/225 - 1s - loss: 0.5013 - accuracy: 0.7994 - val_loss: 0.5298 - val_accuracy: 0.7788 - 625ms/epoch - 3ms/step
Epoch 78/200
225/225 - 1s - loss: 0.5018 - accuracy: 0.7992 - val_loss: 0.5297 - val_accuracy: 0.7788 - 633ms/epoch - 3ms/step
Epoch 79/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5298 - val_accuracy: 0.7788 - 667ms/epoch - 3ms/step
Epoch 80/200
225/225 - 1s - loss: 0.5013 - accuracy: 0.7993 - val_loss: 0.5298 - val_accuracy: 0.7788 - 628ms/epoch - 3ms/step
Epoch 81/200
225/225 - 1s - loss: 0.5011 - accuracy: 0.7993 - val_loss: 0.5299 - val_accuracy: 0.7788 - 619ms/epoch - 3ms/step
Epoch 82/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5297 - val_accuracy: 0.7788 - 533ms/epoch - 2ms/step
Epoch 83/200
225/225 - 1s - loss: 0.5026 - accuracy: 0.7993 - val_loss: 0.5297 - val_accuracy: 0.7788 - 520ms/epoch - 2ms/step
Epoch 84/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5297 - val_accuracy: 0.7788 - 533ms/epoch - 2ms/step
Epoch 85/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5297 - val_accuracy: 0.7788 - 565ms/epoch - 3ms/step
Epoch 86/200
225/225 - 1s - loss: 0.5058 - accuracy: 0.7990 - val_loss: 0.5298 - val_accuracy: 0.7788 - 660ms/epoch - 3ms/step
Epoch 87/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5297 - val_accuracy: 0.7788 - 906ms/epoch - 4ms/step
Epoch 88/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5298 - val_accuracy: 0.7788 - 980ms/epoch - 4ms/step
Epoch 89/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5298 - val_accuracy: 0.7788 - 914ms/epoch - 4ms/step
Epoch 90/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5298 - val_accuracy: 0.7788 - 894ms/epoch - 4ms/step
Epoch 91/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5297 - val_accuracy: 0.7788 - 628ms/epoch - 3ms/step
Epoch 92/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5297 - val_accuracy: 0.7788 - 620ms/epoch - 3ms/step
Epoch 93/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5298 - val_accuracy: 0.7788 - 866ms/epoch - 4ms/step
Epoch 94/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5298 - val_accuracy: 0.7788 - 725ms/epoch - 3ms/step
Epoch 95/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5298 - val_accuracy: 0.7788 - 654ms/epoch - 3ms/step
Epoch 96/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5297 - val_accuracy: 0.7788 - 520ms/epoch - 2ms/step
Epoch 97/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5297 - val_accuracy: 0.7788 - 617ms/epoch - 3ms/step
Epoch 98/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5298 - val_accuracy: 0.7788 - 544ms/epoch - 2ms/step
Epoch 99/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5298 - val_accuracy: 0.7788 - 560ms/epoch - 2ms/step
Epoch 100/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5298 - val_accuracy: 0.7788 - 518ms/epoch - 2ms/step
Epoch 101/200
225/225 - 1s - loss: 0.5015 - accuracy: 0.7993 - val_loss: 0.5298 - val_accuracy: 0.7788 - 552ms/epoch - 2ms/step
Epoch 102/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5299 - val_accuracy: 0.7788 - 644ms/epoch - 3ms/step
Epoch 103/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5297 - val_accuracy: 0.7788 - 647ms/epoch - 3ms/step
Epoch 104/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5298 - val_accuracy: 0.7788 - 655ms/epoch - 3ms/step
Epoch 105/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5298 - val_accuracy: 0.7788 - 588ms/epoch - 3ms/step
Epoch 106/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5298 - val_accuracy: 0.7788 - 581ms/epoch - 3ms/step
Epoch 107/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5298 - val_accuracy: 0.7788 - 579ms/epoch - 3ms/step
Epoch 108/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5298 - val_accuracy: 0.7788 - 594ms/epoch - 3ms/step
Epoch 109/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5298 - val_accuracy: 0.7788 - 598ms/epoch - 3ms/step
Epoch 110/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5298 - val_accuracy: 0.7788 - 679ms/epoch - 3ms/step
Epoch 111/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5298 - val_accuracy: 0.7788 - 735ms/epoch - 3ms/step
Epoch 112/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5297 - val_accuracy: 0.7788 - 772ms/epoch - 3ms/step
Epoch 113/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5297 - val_accuracy: 0.7788 - 558ms/epoch - 2ms/step
Epoch 114/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5297 - val_accuracy: 0.7788 - 547ms/epoch - 2ms/step
Epoch 115/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5297 - val_accuracy: 0.7788 - 523ms/epoch - 2ms/step
Epoch 116/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5298 - val_accuracy: 0.7788 - 580ms/epoch - 3ms/step
Epoch 117/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5298 - val_accuracy: 0.7788 - 527ms/epoch - 2ms/step
Epoch 118/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5297 - val_accuracy: 0.7788 - 523ms/epoch - 2ms/step
Epoch 119/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5298 - val_accuracy: 0.7788 - 525ms/epoch - 2ms/step
Epoch 120/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5298 - val_accuracy: 0.7788 - 650ms/epoch - 3ms/step
Epoch 121/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5298 - val_accuracy: 0.7788 - 521ms/epoch - 2ms/step
Epoch 122/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5298 - val_accuracy: 0.7788 - 512ms/epoch - 2ms/step
Epoch 123/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5298 - val_accuracy: 0.7788 - 503ms/epoch - 2ms/step
Epoch 124/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5297 - val_accuracy: 0.7788 - 587ms/epoch - 3ms/step
Epoch 125/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5297 - val_accuracy: 0.7788 - 564ms/epoch - 3ms/step
Epoch 126/200
225/225 - 0s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5297 - val_accuracy: 0.7788 - 500ms/epoch - 2ms/step
Epoch 127/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5297 - val_accuracy: 0.7788 - 641ms/epoch - 3ms/step
Epoch 128/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5298 - val_accuracy: 0.7788 - 513ms/epoch - 2ms/step
Epoch 129/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5297 - val_accuracy: 0.7788 - 519ms/epoch - 2ms/step
Epoch 130/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5297 - val_accuracy: 0.7788 - 646ms/epoch - 3ms/step

Epoch 131/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5297 - val_accuracy: 0.7788 - 623ms/epoch - 3ms/step
Epoch 132/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5296 - val_accuracy: 0.7788 - 568ms/epoch - 3ms/step
Epoch 133/200
225/225 - 0s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5297 - val_accuracy: 0.7788 - 499ms/epoch - 2ms/step
Epoch 134/200
225/225 - 0s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5296 - val_accuracy: 0.7788 - 499ms/epoch - 2ms/step
Epoch 135/200
225/225 - 0s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5297 - val_accuracy: 0.7788 - 499ms/epoch - 2ms/step
Epoch 136/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5297 - val_accuracy: 0.7788 - 636ms/epoch - 3ms/step
Epoch 137/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5297 - val_accuracy: 0.7788 - 564ms/epoch - 3ms/step
Epoch 138/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5298 - val_accuracy: 0.7788 - 536ms/epoch - 2ms/step
Epoch 139/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5298 - val_accuracy: 0.7788 - 543ms/epoch - 2ms/step
Epoch 140/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5298 - val_accuracy: 0.7788 - 557ms/epoch - 2ms/step
Epoch 141/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5297 - val_accuracy: 0.7788 - 544ms/epoch - 2ms/step
Epoch 142/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5298 - val_accuracy: 0.7788 - 716ms/epoch - 3ms/step
Epoch 143/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5298 - val_accuracy: 0.7788 - 512ms/epoch - 2ms/step
Epoch 144/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5298 - val_accuracy: 0.7788 - 616ms/epoch - 3ms/step
Epoch 145/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5297 - val_accuracy: 0.7788 - 584ms/epoch - 3ms/step
Epoch 146/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5298 - val_accuracy: 0.7788 - 514ms/epoch - 2ms/step
Epoch 147/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5298 - val_accuracy: 0.7788 - 613ms/epoch - 3ms/step
Epoch 148/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5298 - val_accuracy: 0.7788 - 504ms/epoch - 2ms/step
Epoch 149/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5298 - val_accuracy: 0.7788 - 616ms/epoch - 3ms/step
Epoch 150/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5298 - val_accuracy: 0.7788 - 532ms/epoch - 2ms/step
Epoch 151/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5298 - val_accuracy: 0.7788 - 590ms/epoch - 3ms/step
Epoch 152/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5297 - val_accuracy: 0.7788 - 575ms/epoch - 3ms/step
Epoch 153/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5298 - val_accuracy: 0.7788 - 633ms/epoch - 3ms/step
Epoch 154/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5298 - val_accuracy: 0.7788 - 596ms/epoch - 3ms/step
Epoch 155/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5298 - val_accuracy: 0.7788 - 600ms/epoch - 3ms/step
Epoch 156/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5297 - val_accuracy: 0.7788 - 551ms/epoch - 2ms/step
Epoch 157/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5297 - val_accuracy: 0.7788 - 616ms/epoch - 3ms/step
Epoch 158/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5298 - val_accuracy: 0.7788 - 585ms/epoch - 3ms/step
Epoch 159/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5298 - val_accuracy: 0.7788 - 573ms/epoch - 3ms/step
Epoch 160/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5297 - val_accuracy: 0.7788 - 577ms/epoch - 3ms/step
Epoch 161/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5298 - val_accuracy: 0.7788 - 500ms/epoch - 2ms/step
Epoch 162/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5297 - val_accuracy: 0.7788 - 675ms/epoch - 3ms/step
Epoch 163/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5298 - val_accuracy: 0.7788 - 650ms/epoch - 3ms/step
Epoch 164/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5298 - val_accuracy: 0.7788 - 706ms/epoch - 3ms/step
Epoch 165/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5297 - val_accuracy: 0.7788 - 677ms/epoch - 3ms/step
Epoch 166/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5298 - val_accuracy: 0.7788 - 634ms/epoch - 3ms/step
Epoch 167/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5298 - val_accuracy: 0.7788 - 528ms/epoch - 2ms/step
Epoch 168/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5298 - val_accuracy: 0.7788 - 542ms/epoch - 2ms/step
Epoch 169/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5298 - val_accuracy: 0.7788 - 695ms/epoch - 3ms/step
Epoch 170/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5297 - val_accuracy: 0.7788 - 767ms/epoch - 3ms/step
Epoch 171/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5297 - val_accuracy: 0.7788 - 596ms/epoch - 3ms/step
Epoch 172/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5297 - val_accuracy: 0.7788 - 585ms/epoch - 3ms/step
Epoch 173/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5298 - val_accuracy: 0.7788 - 554ms/epoch - 2ms/step
Epoch 174/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5297 - val_accuracy: 0.7788 - 510ms/epoch - 2ms/step
Epoch 175/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5298 - val_accuracy: 0.7788 - 610ms/epoch - 3ms/step
Epoch 176/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5297 - val_accuracy: 0.7788 - 656ms/epoch - 3ms/step
Epoch 177/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5298 - val_accuracy: 0.7788 - 526ms/epoch - 2ms/step
Epoch 178/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5297 - val_accuracy: 0.7788 - 559ms/epoch - 2ms/step
Epoch 179/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5298 - val_accuracy: 0.7788 - 507ms/epoch - 2ms/step
Epoch 180/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5298 - val_accuracy: 0.7788 - 619ms/epoch - 3ms/step
Epoch 181/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5298 - val_accuracy: 0.7788 - 645ms/epoch - 3ms/step
Epoch 182/200
225/225 - 0s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5298 - val_accuracy: 0.7788 - 500ms/epoch - 2ms/step
Epoch 183/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5298 - val_accuracy: 0.7788 - 526ms/epoch - 2ms/step
Epoch 184/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5299 - val_accuracy: 0.7788 - 527ms/epoch - 2ms/step
Epoch 185/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5298 - val_accuracy: 0.7788 - 525ms/epoch - 2ms/step
Epoch 186/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5298 - val_accuracy: 0.7788 - 562ms/epoch - 2ms/step
Epoch 187/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5298 - val_accuracy: 0.7788 - 606ms/epoch - 3ms/step
Epoch 188/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5298 - val_accuracy: 0.7788 - 585ms/epoch - 3ms/step
Epoch 189/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5298 - val_accuracy: 0.7788 - 976ms/epoch - 4ms/step
Epoch 190/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5298 - val_accuracy: 0.7788 - 859ms/epoch - 4ms/step
Epoch 191/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5298 - val_accuracy: 0.7788 - 854ms/epoch - 4ms/step
Epoch 192/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5297 - val_accuracy: 0.7788 - 1s/epoch - 5ms/step
Epoch 193/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5298 - val_accuracy: 0.7788 - 1s/epoch - 4ms/step
Epoch 194/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5298 - val_accuracy: 0.7788 - 1s/epoch - 5ms/step
Epoch 195/200

225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5298 - val_accuracy: 0.7788 - 824ms/epoch - 4ms/step
Epoch 196/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5298 - val_accuracy: 0.7788 - 910ms/epoch - 4ms/step
Epoch 197/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5298 - val_accuracy: 0.7788 - 517ms/epoch - 2ms/step
Epoch 198/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5298 - val_accuracy: 0.7788 - 532ms/epoch - 2ms/step
Epoch 199/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5298 - val_accuracy: 0.7788 - 588ms/epoch - 3ms/step
Epoch 200/200
225/225 - 1s - loss: 0.5014 - accuracy: 0.7993 - val_loss: 0.5298 - val_accuracy: 0.7788 - 583ms/epoch - 3ms/step

In [27]:
y_predict= classifier.predict(x_test)
y_predict

63/63 [==============================] - 0s 2ms/step

array([[0.20067842],
       [0.20067842],
       [0.20067842],
       ...,
       [0.20067842],
       [0.20067842],
       [0.20067842]], dtype=float32)

In [28]:
y_predict=(y_predict>0.5).astype(int)

In [29]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [30]:
acc = accuracy_score(y_test,y_predict)
acc

0.7925

In [32]:
cm = confusion_matrix(y_test,y_predict)
cm

array([[1585,    0],
       [ 415,    0]], dtype=int64)

In [33]:
print(((cm[0][0] + cm[1][1])* 100) / len(y_test), '% of data was classified correctly')

79.25 % of data was classified correctly